name: SpreadsheetにPull Requestの情報を送信
on:
  pull_request:
    branches:
      - develop
      - feature/*
    types:
      - closed
jobs:
  metrix-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: post github info
        run: |
          gh api graphql -f id="${{ github.event.pull_request.node_id }}" -f query='
            query ($id: ID!) {
              node(id: $id) {
                ... on PullRequest {
                  repository {
                    name
                  }
                  title
                  author {
                    login
                  }
                  url
                  headRefName
                  commits(first: 1) {
                    nodes {
                      commit {
                        authoredDate
                      }
                    }
                  }
                  createdAt
                  mergedAt
                  additions
                  deletions
                  changedFiles
                  reviews(last: 1) {
                    nodes {
                      ... on PullRequestReview {
                        createdAt
                      }
                    }
                  }
                }
              }
            }
          ' |
          # tokenで認証を行なっている
          jq -r --arg token ${{ secrets.GAS_POST_API_METRIX_TOKEN }} '.data.node |
            {
              data: {
                repository: .repository.name,
                title: .title,
                user: .author.login,
                url: .url,
                head: .headRefName,
                firstCommittedAt: .commits.nodes[0].commit.authoredDate,
                createdAt: .createdAt,
                lastReviewedAt: .reviews.nodes[0].createdAt,
                mergedAt: .mergedAt,
                additions: .additions,
                deletions: .deletions,
                changedFiles: .changedFiles
              },
              type: "lead_time",
              token: $token
            } |
            @json' |
          curl -L -H "Content-Type: application/json" -d @- "https://script.google.com/macros/s/AKfycbx8l5vFT9J6fkwz1p1z-c7pdW_1bhm-2CNk-JL2ayPYgf0l-Ef9W3HPU6_-c6aOZSR8uQ/exec"
